#!/usr/bin/env bash
# Install nginx on my server
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
sudo systemctl enable nginx
sudo apt install net-tools
ifconfig
sudo chmod 766 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
curl 107.22.142.139
sudo chmod 755 /var/www/html/index.nginx-debian.html
