#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
sudo systemctl enable nginx
sudo apt install net-tools
ifconfig
sudo chmod 777 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
curl 107.22.142.139
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/africaexchange.com permanent;/" /etc/nginx/sites-available/default ;
sudo sed -i "s/server_name _;/server_name _;\n\terror_page 404 /404.html;\nlocation = /404.html{\ninternal;}/" /etc/nginx/sites-available/default ;
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo /etc/init.d/nginx start
else
    sudo /etc/init.d/nginx restart
fi
sudo chmod 755 /var/www/html/index.nginx-debian.html
sudo chmod 755 /etc/nginx/sites-available/default
