#!/usr/bin/env bash
# Install nginx on my server
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx start
sudo systemctl enable nginx
sudo apt install net-tools
ifconfig
