#!/usr/bin/env bash
# Configure nginx as nginx user, listening to port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
